name: Laravel Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: myql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
         - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup php
        uses: shivammathur/setup-php@v2
        with: 
          php-version: '8.2'
      - name: install composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader
      - name: cp .env.example
        run: cp .env.example .env
      - name: key generate
        run: php artisan key:generate
      - name: Set DB environment variables
        run: |
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=testing" >> .env
          echo "DB_USERNAME=user" >> .env
          echo "DB_PASSWORD=password" >> .env
